### ISSUE TITLE
Check class of datetime in sample data

### ISSUE THREAD

**Issue by samzipper** [HEAL-KGS/STICr#25]
The class of the `datetime` column varies among sample datasets:

 - in `calibrated_stic_data`, it is character
 - in `classified_df`, it is posixct
 - in `tidy_stic_data` it is posixct

I think it should be switched to posix in `calibrated_stic_data` unless there is a reason that it is not?

**Comment by christopherwheeler** [comment]
changed calibrated_stic_data datetime col to posixct
