### ISSUE TITLE
Reduce size of examples/simplify naming

### ISSUE THREAD

**Issue by samzipper** [HEAL-KGS/STICr#6]
Suggest trimming the example down to a smaller file covering a shorter time duration, but should still include both wet and dry periods.

Also, perhaps change test data file names to be shorter and more descriptive of content. Maybe something like:
 - `raw_hobo_data`
 - `tidy_stic_data`
 - `calibrated_stic_data`
 - `calibration_standard_data`
Something like that?

**Comment by christopherwheeler** [comment]
Shortened and changed example df names to those you suggested!
